# Task descriptions for each Hemlock codex program.
# Maps (category, task_name) -> natural-English task description.

DESCRIPTIONS = {
    # ---------------- algorithms/sorting ----------------
    ("algorithms/sorting", "bubble_sort"): "Implement bubble sort. Sort the array [64, 34, 25, 12, 22, 11, 90, 1, 45, 78] in ascending order and print the sorted values as a space-separated string.",
    ("algorithms/sorting", "insertion_sort"): "Implement insertion sort. Sort the array [64, 34, 25, 12, 22, 11, 90, 1, 45, 78] in ascending order and print the sorted values as a space-separated string.",
    ("algorithms/sorting", "selection_sort"): "Implement selection sort. Sort the array [64, 34, 25, 12, 22, 11, 90, 1, 45, 78] in ascending order and print the sorted values as a space-separated string.",
    ("algorithms/sorting", "merge_sort"): "Implement merge sort using a recursive divide-and-merge approach. Sort the array [64, 34, 25, 12, 22, 11, 90, 1, 45, 78] and print the sorted values as a space-separated string.",
    ("algorithms/sorting", "quicksort"): "Implement quicksort with Lomuto partitioning using the last element as pivot. Sort the array [64, 34, 25, 12, 22, 11, 90, 1, 45, 78] in place and print the sorted values as a space-separated string.",
    ("algorithms/sorting", "heap_sort"): "Implement heap sort by building a max-heap and repeatedly extracting the largest element. Sort the array [64, 34, 25, 12, 22, 11, 90, 1, 45, 78] and print the sorted values as a space-separated string.",
    ("algorithms/sorting", "counting_sort"): "Implement counting sort for an array of non-negative integers. Sort [64, 34, 25, 12, 22, 11, 90, 1, 45, 78] and print the sorted values as a space-separated string.",
    ("algorithms/sorting", "radix_sort"): "Implement LSD radix sort using counting sort as the stable subroutine on each decimal digit. Sort the array [64, 34, 25, 12, 22, 11, 90, 1, 45, 78] and print the sorted values as a space-separated string.",

    # ---------------- algorithms/search ----------------
    ("algorithms/search", "binary_search_iterative"): "Implement iterative binary search on a sorted array. Using the array [2, 5, 8, 12, 16, 23, 38, 56, 72, 91], search for 23 (present) and 50 (absent), printing the found index or a not-found message for each.",
    ("algorithms/search", "binary_search_recursive"): "Implement recursive binary search on a sorted array. Using the array [2, 5, 8, 12, 16, 23, 38, 56, 72, 91], search for 23 (present) and 50 (absent), printing the found index or a not-found message for each.",
    ("algorithms/search", "linear_search_sentinel"): "Implement linear search with a sentinel value placed at the end of the array to eliminate the bounds check inside the loop. Using the array [2, 5, 8, 12, 16, 23, 38, 56, 72, 91], search for 23 and 50 and print the results.",
    ("algorithms/search", "interpolation_search"): "Implement interpolation search, which estimates the target position using linear interpolation over the value range. Using the array [2, 5, 8, 12, 16, 23, 38, 56, 72, 91], search for 23 and 50 and print the results.",

    # ---------------- algorithms/trees ----------------
    ("algorithms/trees", "bst_insert_search_delete"): "Implement a binary search tree with insert, search, and delete operations. Insert the values 50, 30, 70, 20, 40, 60, 80, search for 40 and 25, delete 30, and then print the in-order traversal of the remaining tree.",
    ("algorithms/trees", "bst_inorder"): "Build a binary search tree by inserting the values 50, 30, 70, 20, 40, 60, 80, then perform an in-order traversal and print the visited values as a space-separated string.",
    ("algorithms/trees", "bst_levelorder"): "Build a binary search tree by inserting the values 50, 30, 70, 20, 40, 60, 80, then perform a level-order (BFS) traversal using a queue and print the visited values as a space-separated string.",
    ("algorithms/trees", "avl_tree"): "Implement a self-balancing AVL tree with left, right, left-right, and right-left rotations. Insert the values 10, 20, 30, 40, 50, 25, then print the in-order traversal.",
    ("algorithms/trees", "trie"): "Implement a trie with insert, exact-match search, and prefix-check operations. Insert the words \"apple\", \"app\", \"application\", \"bat\", \"ball\", then run a mix of search and prefix queries and print each result.",
    ("algorithms/trees", "expression_tree"): "Build an expression tree for (2 + 3) * (4 - 1) by constructing operator and operand nodes, then recursively evaluate the tree and print the resulting value.",
    ("algorithms/trees", "lowest_common_ancestor"): "Build a binary search tree from the values 50, 30, 70, 20, 40, 60, 80, then find and print the lowest common ancestor for the pairs (20, 40), (20, 70), and (60, 80).",

    # ---------------- algorithms/graphs ----------------
    ("algorithms/graphs", "dijkstra"): "Implement Dijkstra's shortest-path algorithm on a weighted directed graph using a HashMap-based priority queue. Find the shortest path and distance from A to E in a small 5-node graph, then print the distance and reconstructed path.",
    ("algorithms/graphs", "bfs_shortest"): "Implement breadth-first search to find the shortest path in an unweighted directed graph. On a 6-node adjacency list, compute the shortest distance and path from node 0 to node 5 and print both.",
    ("algorithms/graphs", "dfs"): "Implement iterative depth-first search on a directed graph using an explicit stack. Starting from node 0 on a 6-node adjacency list, print the DFS visitation order as a space-separated string.",
    ("algorithms/graphs", "topological_sort"): "Implement Kahn's algorithm for topological sorting of a DAG using in-degree counts and a queue. On a 6-node graph, print the resulting topological order as a space-separated string.",
    ("algorithms/graphs", "floyd_warshall"): "Implement the Floyd-Warshall all-pairs shortest-paths algorithm on a 4-node directed weighted graph. Print the resulting distance matrix with \"INF\" for unreachable pairs.",
    ("algorithms/graphs", "prim_mst"): "Implement Prim's minimum spanning tree algorithm on a 5-node undirected weighted graph represented as an adjacency matrix. Print each MST edge with its weight and the total MST weight.",
    ("algorithms/graphs", "kruskal_mst"): "Implement Kruskal's minimum spanning tree algorithm using a union-find (disjoint-set) structure with path compression and union by rank. Sort edges by weight, build the MST on a 5-node graph, and print each selected edge and the total weight.",
    ("algorithms/graphs", "cycle_detection"): "Detect cycles in a directed graph using iterative DFS with three-color (white/gray/black) vertex coloring. Test two small graphs, one containing a cycle and one that is a DAG, and print whether each has a cycle.",
    ("algorithms/graphs", "astar"): "Implement A* pathfinding on a 5x5 grid with obstacles using the Manhattan distance heuristic. Find a path from (0,0) to (4,4) and print the path length and the sequence of (row, col) coordinates.",

    # ---------------- algorithms/dp ----------------
    ("algorithms/dp", "lcs"): "Use dynamic programming to find the longest common subsequence of two strings. For a = \"ABCBDAB\" and b = \"BDCAB\", build the DP table, backtrack to recover the subsequence, and print its length and value.",
    ("algorithms/dp", "lis"): "Use O(n^2) dynamic programming to find the length of the longest strictly increasing subsequence. For the array [10, 9, 2, 5, 3, 7, 101, 18], print the LIS length.",
    ("algorithms/dp", "knapsack"): "Solve the 0/1 knapsack problem using a 2D dynamic programming table. Given weights [2, 3, 4, 5], values [3, 4, 5, 6], and capacity 8, compute and print the maximum achievable value.",
    ("algorithms/dp", "edit_distance"): "Compute the Levenshtein edit distance (minimum insertions, deletions, and substitutions) between two strings using dynamic programming. For a = \"kitten\" and b = \"sitting\", print the edit distance.",
    ("algorithms/dp", "coin_change"): "Use dynamic programming to find the minimum number of coins needed to make a target amount. Given coin denominations [1, 5, 10, 25] and amount 36, print the minimum count (or -1 if impossible).",
    ("algorithms/dp", "matrix_chain"): "Solve the matrix-chain multiplication problem using dynamic programming over chain lengths to find the minimum scalar multiplications needed. For dimensions [10, 30, 5, 60], print the minimum multiplication count.",
    ("algorithms/dp", "fibonacci_memo"): "Compute the nth Fibonacci number using bottom-up dynamic programming with an object as a memoization table. For n = 40, print the result.",
    ("algorithms/dp", "rod_cutting"): "Solve the rod-cutting problem with dynamic programming, where prices[i] is the price for a piece of length i. For prices = [0, 1, 5, 8, 9, 10, 17, 17, 20] and rod length 8, print the maximum obtainable revenue.",

    # ---------------- algorithms/classic ----------------
    ("algorithms/classic", "two_sum"): "Solve the two-sum problem: given the array [2, 7, 11, 15] and target 9, use a HashMap to find two indices whose values sum to the target in a single pass. Print the pair of indices.",
    ("algorithms/classic", "linked_list_reverse"): "Build a singly linked list from [1, 2, 3, 4, 5] using object nodes, then reverse it in place by re-pointing next references. Print the original and reversed lists.",
    ("algorithms/classic", "bracket_matching"): "Check whether strings of parentheses, curly braces, and square brackets are balanced using a stack. Test \"({[]})\", \"({[}])\", and the empty string, printing the result for each.",
    ("algorithms/classic", "queue_two_stacks"): "Implement a FIFO queue using two stacks (an inbox and an outbox) where dequeue moves elements between stacks when the outbox is empty. Run a sequence of enqueues and dequeues and print the dequeued values.",
    ("algorithms/classic", "priority_queue"): "Implement a min-priority queue as a binary heap backed by an array, with insert (sift up) and extract-min (sift down) operations. Insert [5, 3, 7, 1, 4, 2], then extract all elements and print them in sorted order.",
    ("algorithms/classic", "lru_cache"): "Implement an LRU cache of capacity 3 using a doubly linked list plus a HashMap for O(1) get/put with eviction of the least-recently-used entry. Run a sequence of puts and gets and log the hit/miss/eviction behavior for each.",
    ("algorithms/classic", "ring_buffer"): "Implement a fixed-capacity ring buffer over a raw allocated pointer, with head/tail indices and wrap-around modulo arithmetic. Demonstrate writes, reads, and wrap behavior on a capacity-4 buffer, then free the backing memory.",
    ("algorithms/classic", "string_permutations"): "Generate all permutations of the string \"abc\" using recursive swap-based permutation. Print each permutation on its own line.",

    # ---------------- systems/memory ----------------
    ("systems/memory", "manual_linked_list"): "Build a singly linked list using manual memory management: each node is a 12-byte block allocated with alloc() containing an i32 value followed by a pointer to the next node. Push 10, 20, 30, traverse and print the list, then free every node and report the count.",
    ("systems/memory", "dynamic_array"): "Implement a growable dynamic array of i32 backed by a raw pointer from alloc(). When the array fills, allocate a new block of double capacity, memcpy the old data, and free the old buffer. Push the values 1 through 10, print the final capacity and contents, then free the backing memory.",
    ("systems/memory", "arena_allocator"): "Implement a simple bump arena allocator over a 1024-byte block obtained from alloc(), handing out regions by advancing an offset. Allocate several i32 slots, write and read back values, print the bytes used, then free the whole arena at once.",
    ("systems/memory", "memory_pool"): "Implement a fixed-size slab allocator (object pool) of 8 slots of 8 bytes each, backed by a single alloc() and a boolean free list. Allocate and free slots to show reuse, track the active count, and free the pool at the end.",
    ("systems/memory", "deque_pointers"): "Implement a double-ended queue with manually allocated doubly linked list nodes (24 bytes per node holding an i32 value plus previous and next pointers). Perform push_front, push_back, pop_front, and pop_back operations, printing the state along the way, and free every remaining node before exiting.",
    ("systems/memory", "buffer_builder"): "Implement a growing byte buffer on top of the safe buffer type that doubles its capacity when full, using buffer_ptr and memcpy to copy data to the new allocation. Write the bytes of \"Hello, World!\" one at a time, then reconstruct and print the string.",
    ("systems/memory", "struct_of_arrays"): "Store 5 3D points in a struct-of-arrays (SoA) layout using three parallel raw pointers for x, y, and z coordinates (f64 each). Compute the distance of each point from the origin, print the coordinates and distance, then free all three arrays.",
    ("systems/memory", "reference_counting"): "Implement manual reference counting for objects stored as 8-byte raw allocations (4 bytes refcount, 4 bytes i32 data). Provide new/retain/release helpers, demonstrate shared ownership across multiple references, and free the memory when the count reaches zero.",

    # ---------------- systems/concurrency ----------------
    ("systems/concurrency", "producer_consumer"): "Implement a single producer and single consumer communicating through a channel. The producer sends the values 1 through 10 and closes the channel; the consumer receives until close and prints the collected values as a space-separated string.",
    ("systems/concurrency", "fan_out_fan_in"): "Distribute the values 1 through 20 to four worker tasks over a work channel, have each worker square its input and send to a result channel, then collect and sort the squares and print them.",
    ("systems/concurrency", "pipeline"): "Build a three-stage channel pipeline: one stage generates the numbers 1 through 5, the next doubles each value, and the third adds 10. Spawn each stage as an async task, collect the final results, and print them space-separated.",
    ("systems/concurrency", "barrier_sync"): "Implement a barrier synchronization primitive using an atomic counter in allocated memory. Spawn 4 tasks that increment the counter on arrival and spin-wait until all have arrived, then signal completion through a channel and print how many tasks passed the barrier.",
    ("systems/concurrency", "atomic_counter"): "Implement a lock-free shared counter using atomic_add_i32 on an allocated i32. Spawn 10 tasks that each perform 100 increments, join them, then print the final counter value (expected 1000).",
    ("systems/concurrency", "parallel_merge_sort"): "Implement a parallel merge sort by spawning an async task for each recursive half and joining to collect the sorted halves before merging. Sort [38, 27, 43, 3, 9, 82, 10, 55] and print the sorted result.",
    ("systems/concurrency", "dining_philosophers"): "Solve the dining philosophers problem for 5 philosophers, using single-capacity channels as per-fork mutexes and resource ordering (always pick up the lower-numbered fork first) to prevent deadlock. Spawn all philosophers, let each eat once, and print a completion message.",
    ("systems/concurrency", "thread_safe_queue"): "Use a buffered channel as a thread-safe queue shared by 3 producer tasks and 1 consumer task. Each producer pushes 5 tagged items; the consumer reads all 15, then the collected items are sorted and printed.",
    ("systems/concurrency", "map_reduce"): "Implement a map-reduce pipeline on the array [1, 2, 3, 4, 5, 6, 7, 8]. Split into chunks of 2, spawn a mapper task per chunk that squares each element, concatenate all squared values, then run a single reducer task that sums them and prints the total.",
    ("systems/concurrency", "async_file_processing"): "Process 3 simulated CSV files in parallel by spawning one async task per file that computes the sum, max, and count of its data array. Join all tasks and print a per-file summary followed by a completion message.",

    # ---------------- systems/defer ----------------
    ("systems/defer", "file_defer_close"): "Open a file and use defer to guarantee it is closed when the function returns. Write a known string to the file, read it back, and print a success message if the content matches.",
    ("systems/defer", "alloc_defer_free"): "Allocate three raw memory blocks with alloc() and schedule a free() for each using defer so cleanup is guaranteed on function return. Write and read back an i32 from each block and print the values and a final \"all memory freed\" message.",
    ("systems/defer", "nested_cleanup"): "Demonstrate nested defer execution through three functions (outer calls middle calls inner), where each function defers a cleanup print. Run the outermost call and observe that deferred statements run in reverse order as each function returns.",
    ("systems/defer", "error_cleanup_defer"): "Show that deferred cleanup still runs when a function throws. Allocate memory, register defer free() and defer cleanup(), then throw from the function and catch it in the caller, verifying that both deferred actions executed.",

    # ---------------- translation/python ----------------
    ("translation/python", "word_frequency"): "Build a word frequency counter for the sentence \"the cat sat on the mat the cat\" using a HashMap. Then collect the entries into an array, sort them by count descending, and print each \"word: count\" pair.",
    ("translation/python", "list_comprehension"): "Generate the integers 1 through 10, then use a .filter().map() chain to keep the even numbers and square them. Print the results as a space-separated string (expected: 4 16 36 64 100).",
    ("translation/python", "context_manager"): "Use defer to guarantee file cleanup in a scope-based pattern. Write the string \"hello from context manager\" to /tmp/hemlock_ctx.txt with defer f.close(), then reopen the same file in another function (also using defer close) and print its contents.",
    ("translation/python", "generator_pattern"): "Simulate a lazy Fibonacci generator using a closure that captures two state variables and returns the next value on each call. Call the generator 10 times and print the results as a space-separated string.",
    ("translation/python", "class_to_define"): "Model a bank account using a define type with owner and balance fields and standalone functions for deposit, withdraw, and get_balance that take the account as an explicit first argument. Deposit 50 and withdraw 30 from an account starting at 100, demonstrate that withdrawing 500 throws an \"Insufficient funds\" error caught by the caller, and print each balance transition.",
    ("translation/python", "decorator_pattern"): "Implement a higher-order function that wraps another function to log \"Calling <name>\" before and \"<name> returned <value>\" after each call. Apply this wrapper to an add and multiply function and invoke both.",
    ("translation/python", "csv_processing"): "Parse a CSV string with the header name,age,score and 5 data rows. Filter rows with score >= 85, print each high scorer's name and score, then compute and print the average score among the high scorers.",
    ("translation/python", "json_transform"): "Parse a JSON document containing a users array where each user has name, age, and active fields. Filter to only active users, extract their names, wrap them in a new object {active_names, count}, and print the serialized JSON.",
    ("translation/python", "regex_findall"): "Extract every sequence of digits from the string \"Order 42 has 3 items weighing 17 kg at price 99\" using the POSIX regex module. Print each number on its own line followed by the total count.",
    ("translation/python", "argparse_example"): "Parse CLI arguments using @stdlib/args with support for --name, --count, and a --upper flag. Using a hard-coded argv of [\"script.hml\", \"--name\", \"Alice\", \"--count\", \"3\", \"--upper\"], print the parsed option values, then print the greeting \"Hello, <name>!\" count times, uppercased when the flag is set.",

    # ---------------- translation/javascript ----------------
    ("translation/javascript", "promise_all"): "Run several async computations in parallel and collect all their results. Define an async square function, spawn it for inputs 1, 2, and 3, join all tasks, and print the results (expected: 1 4 9).",
    ("translation/javascript", "async_await"): "Chain three async stages sequentially (fetch_data, process_data, save_results) where each task prints its step, sleeps briefly, and returns a value that is passed to the next stage via spawn/join. Print \"done\" after the last stage completes.",
    ("translation/javascript", "array_chain"): "Using the array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], build a single .map().filter().reduce() chain that squares each value, keeps only results greater than 20, and sums them. Print the final total (expected: 355).",
    ("translation/javascript", "event_emitter"): "Implement a publish/subscribe pattern using a channel as the event bus. Spawn a subscriber task that receives and prints messages until it sees \"done\", publish \"hello\", \"world\", \"hemlock\", and \"done\" from the main task, then wait for the subscriber.",
    ("translation/javascript", "fetch_api"): "Demonstrate an HTTP-style fetch-and-parse pattern. Simulate a GET response object with a status and JSON body, then in a try/catch print the status and parse the body with @stdlib/json, handling any parse error.",
    ("translation/javascript", "set_timeout"): "Schedule three delayed actions concurrently by spawning async tasks that sleep for 0.1s, 0.2s, and 0.3s before printing a label. Print \"all scheduled\" immediately, join the tasks, and print \"all complete\" at the end.",
    ("translation/javascript", "object_spread"): "Merge configuration objects using the object spread operator. Given defaults {host, port, debug} and user overrides {port, debug}, build a merged config with an added name field where later spreads override earlier ones, and print each resulting field. Then build an immutable update that changes only the port and print both old and new values.",
    ("translation/javascript", "template_literals"): "Demonstrate template strings with `${...}` interpolation: simple variable substitution, arithmetic expressions, boolean comparisons, method calls on arrays and strings, and accessing fields on an object literal. Print a handful of formatted lines exercising each case.",
    ("translation/javascript", "try_catch_finally"): "Define a risky_operation function that throws \"negative value\" for negative input and \"zero value\" for zero, wrapped in try/catch/finally that always prints a cleanup message. Call it with 42, -1, and 0 to show the success, catch, and finally paths.",
    ("translation/javascript", "map_set"): "Exercise the HashMap and Set collections from @stdlib/collections. Populate a HashMap with several string keys, check has, get a value, delete a key, and print the sorted keys; populate a Set with duplicates to show dedup, print its size and sorted values, and verify membership with has.",

    # ---------------- translation/c ----------------
    ("translation/c", "malloc_free"): "Use manual memory management to hold 10 i32 values: allocate a 40-byte block with alloc(), write i*i into each slot using ptr_offset and ptr_write_i32, read the values back and print them space-separated, then free the block.",
    ("translation/c", "struct_functions"): "Define Point and Vector2D as define types with f64 x, y fields. Implement point_add, vec_scale, and vec_magnitude as standalone functions that take the objects as arguments. Demonstrate each on sample points and print the results.",
    ("translation/c", "linked_list"): "Build a singly linked list of integers using object nodes with value and next fields. Push the numbers 5, 4, 3, 2, 1 so traversal order is 1 through 5, then walk the list and print its contents on one line.",
    ("translation/c", "file_io"): "Open /tmp/hemlock_file_io_test.txt for writing, write three newline-separated lines, close it, then reopen for reading, read the entire contents and print them. Finally, delete the file with a shell exec and print a completion message.",
    ("translation/c", "string_ops"): "Demonstrate common string operations on \"Hello, World!\" using Hemlock's built-in string methods: length, concatenation with +, equality and ordering comparisons, find, replace, to_upper, starts_with, contains, and splitting/joining a CSV string.",
    ("translation/c", "bit_manipulation"): "Implement set_bit, clear_bit, toggle_bit, check_bit, and a popcount helper using the &, |, ^, ~, <<, and >> operators. Set bits 0, 3, and 7 in an integer, check and toggle selected bits, and print the intermediate and final values along with some left/right shift examples.",
    ("translation/c", "signal_handling"): "Register a handler for SIGUSR1 using @stdlib/signal that sets a flag and prints the caught signal number. Send SIGUSR1 to the current process by execing \"kill -USR1 <pid>\" and then print whether the handler ran.",
    ("translation/c", "fork_exec"): "Spawn three child tasks (replacing fork/exec) each of which computes the sum of integers 0..999 and prints its id and result. Join all three and print a final message from the parent.",
    ("translation/c", "pthread_spawn"): "Parallelize summing the integers 1 through 100 across 4 worker tasks. Each worker receives a start and end range, returns its partial sum, and the main task joins all workers and prints the combined total.",
    ("translation/c", "socket_server"): "Demonstrate a TCP-style echo server pattern using two channels as the request/response transport. A server task reads messages and echoes them back prefixed with \"echo: \"; a client task sends \"hello\", \"world\", \"goodbye\", prints each reply, and signals done with a null.",

    # ---------------- translation/go ----------------
    ("translation/go", "goroutine_fanout"): "Implement a fan-out/fan-in worker pool using channels. Send the jobs 1 through 12 into a jobs channel, spawn 4 worker tasks that square each received job and write to a results channel, join all workers, collect the results, sort them, and print them space-separated.",
    ("translation/go", "waitgroup"): "Replace Go's sync.WaitGroup with an array of task handles. Spawn 5 async tasks that each print \"task <id> done\", join all of them, and then print \"all 5 tasks done\".",
    ("translation/go", "select_channel"): "Simulate Go's select statement using relay tasks that forward from multiple source channels into a single result channel. Spawn two senders on separate channels, forward both into a merged channel, receive the first arriving value and print it, then drain and join the remaining tasks and close all channels.",
    ("translation/go", "defer_go"): "Show LIFO defer semantics. In one function, schedule three deferred prints followed by a regular print of \"end\"; in another, schedule a defer inside a loop with index 0, 1, 2 and then print \"after loop\". Call both functions and observe the reverse-order output.",
    ("translation/go", "error_handling"): "Use throw and try/catch to replace the Go (value, error) return pattern. Implement divide that throws on division by zero and parse_positive that throws on non-digit characters or non-positive results, then exercise each function with both successful and failing inputs, printing either the result or the caught error message.",
    ("translation/go", "mutex_atomic"): "Replace sync.Mutex with lock-free atomics on shared memory. Allocate a 4-byte counter, spawn 5 tasks that each call atomic_add_i32 200 times, join all tasks, print the final value (expected 1000), and free the counter.",

    # ---------------- translation/rust ----------------
    ("translation/rust", "vec_operations"): "Exercise dynamic array methods. Push 5, 3, 8, 1, 4 onto an empty array, pop one value, then derive arrays for doubled values, even values, and a sorted copy, and check membership and length. Print each intermediate array.",
    ("translation/rust", "option_result"): "Model Option and Result patterns without explicit types. Implement find_user returning a name or null (Option) and parse_port that throws on an invalid or out-of-range port (Result). Test find_user with ids 1 and 99 using null checks and parse_port with \"8080\", \"abc\", and \"99999\" inside try/catch, printing the outcome of each case.",
    ("translation/rust", "ownership_manual"): "Demonstrate manual memory management in place of Rust's ownership. Allocate an i32 array with 5 entries via alloc(), populate it through ptr_offset and ptr_write_i32, pass the pointer to a sum helper (like a borrow), pass it again to a transform helper that doubles each element in place (like a move/return), and finally call free() to release the block.",
    ("translation/rust", "arc_mutex"): "Replace Arc<Mutex<i32>> with a raw allocated counter and atomic operations. Allocate 4 bytes, store 0, spawn 4 tasks that each call atomic_add_i32 100 times, join them, load and print the final value, and free the memory.",
    ("translation/rust", "iterator_chains"): "Chain array operations without lazy iterators. Generate the numbers 1..=20, print the range, filter evens, square them, reduce to a sum, then perform a single chained filter-by-multiple-of-3 / map add 10 / reduce sum pipeline, and finally build and print a list of five formatted \"item_N\" strings.",
    ("translation/rust", "pattern_matching"): "Use the match expression with value literals, OR patterns, guards, variable binding, and string matching. Implement a classify function categorizing integers, a describe_value function, a greet function over language codes, and a score-to-grade mapping, and print results for several sample inputs.",

    # ---------------- practical ----------------
    ("practical", "http_server"): "Simulate an HTTP server using channels for requests and responses. A server task handles GET requests for \"/\", \"/about\", and any other path (returning 404 Not Found) and sends back status and body; a client task sends three requests and prints each formatted response.",
    ("practical", "cli_tool"): "Build a CLI tool with argument-parsing semantics for --verbose/-v, --output/-o, --format/-f, and --count/-n, maintaining a config object with defaults. Apply a hard-coded sequence of flags, print the tool name and version, and print each resulting configuration field.",
    ("practical", "file_watcher"): "Monitor a file at /tmp/hemlock_watch_test.txt for changes using @stdlib/fs and @stdlib/time. Write an initial line, capture the timestamp, read it back, rewrite with new content, capture a second timestamp, read again, and report whether the content changed and whether the modification time advanced.",
    ("practical", "simple_chat"): "Model a two-person chat between Alice and Bob using a pair of channels (one for each direction). Spawn both participants as async tasks, have them exchange three messages each printing what they received, join both tasks, and print \"Chat ended.\".",
    ("practical", "json_config"): "Load and merge JSON configuration. Start with a defaults object (host, port, debug, log_level, max_connections, timeout), parse a JSON string of user overrides, merge the two with safe-navigation null checks so user values win, and pretty-print the defaults, overrides, and final merged config.",
    ("practical", "log_parser"): "Parse an array of 8 log lines of the form \"YYYY-MM-DD HH:MM:SS [LEVEL] message\". Extract the log level, timestamp, and message from each line, count INFO, WARN, and ERROR entries, then print a summary followed by the timestamp and message of every ERROR line.",
    ("practical", "markdown_to_html"): "Build a small Markdown-to-HTML converter. Support H1/H2/H3 headings, list items starting with \"- \", and inline **bold**, *italic*, and `code` transformations; wrap remaining non-empty lines in <p> tags. Convert a sample Markdown document and print the resulting HTML.",
    ("practical", "base64_codec"): "Implement base64 encoding and decoding from scratch using bit shifts and a 64-character alphabet, including \"=\" padding. Encode \"Hello, World!\", verify the result equals \"SGVsbG8sIFdvcmxkIQ==\", then decode it back and verify the round-trip matches the original.",
    ("practical", "simple_repl"): "Build a tiny calculator REPL with a hard-coded list of input expressions. Tokenize each expression into numbers and +, -, *, / operators, evaluate strictly left-to-right without precedence, and print each input alongside its result (as an integer when whole, otherwise as a float).",
    ("practical", "test_runner"): "Build a minimal test harness that records {name, actual, expected} assertions in an array, then prints PASS/FAIL for each and a final summary of passed/total tests. Register a handful of string, array, and math assertions and run them.",
    ("practical", "sqlite_crud"): "Demonstrate CRUD operations against an in-memory SQLite database using @stdlib/sqlite. Create a users table, insert 4 rows with parameterized placeholders, query all rows and a filtered subset (age > 28), update Alice's age, delete Charlie, print the remaining users and a row count, then close the database.",
    ("practical", "url_shortener"): "Implement a URL shortener backed by two in-memory object maps (long->short and short->long) and an incrementing numeric counter encoded in base62. Shorten several URLs including a duplicate, resolve a short URL back to its original, and verify that repeated calls for the same long URL return the same short URL.",
}
